language: python
dist: focal
python:
 - "3.8"
 - "3.9"
 - "3.10"
before_install:
  - sudo apt-get -y install libsnappy-dev
install:
  - pip install -U pytest pytest-console-scripts pytest-check
  - python3 setup.py install
#  - pip uninstall -y protobuf
#  - pip install protobuf
script:
  - PYTHONPATH=src python3 -m pytest tests
