language: python
dist: jammy
python:
 - "3.8"
 - "3.9"
 - "3.10"
 - "3.11-dev"
before_install:
  - sudo apt-get -y install libsnappy-dev python3-setuptools
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest
