language: python
dist: focal
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
 - "3.10"
before_install:
  - sudo apt-get -y install libsnappy-dev
  - pip show protobuf
install:
  - pip install -U pytest pytest-console-scripts pytest-check
  - python3 setup.py install
script:
  - PYTHONPATH=src python3 -m pytest tests
