[tool.poetry]
name = "numbers-parser"
version = "4.0.0"
description = "Read and write Apple Numbers spreadsheets"
authors = ["Jon Connell <python@figsandfudge.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "numbers_parser", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
pendulum = "^2.1.2"
protobuf = "^3.20.1"
python-snappy = "^0.6.1"
compact-json = "^1.1.3"
regex = "^2022.9.13"
roman = "^3.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-check = "^1.0.10"
pytest-console-scripts = "^1.3.1"
pylama = "^8.4.1"
black = {version = "^22.10.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
