name: Code coverage
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
    - name: Generate coverage report
      run: |
        sudo apt-get -y install libsnappy-dev
        # easy_install failing for >= 3.10
        python3 -m pip install pendulum
        python3 -m pip install --upgrade pip
        python3 -m pip install -U pytest pytest-console-scripts pytest-check pytest-cov
        python3 -m pip install -U "protobuf>=3.20.1" python-snappy compact-json regex roman
        python3 setup.py install
        PYTHONPATH=src python3 -m pytest --cov= --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true