name: Code coverage
on: [push, workflow_dispatch]
jobs:
  run:
    runs-on: macos-latest
    env:
      OS: macos-latest
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        pip install pytest pytest-check pytest-console-scripts python-snappy pytest-cov
        PYTHONPATH=src python3 -m pytest --cov= --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true